project:
  type: website

website:
  title: "Julie Xian"
  favicon: "images/dna_icon.png"

format:
  html:
    theme:
      dark: slate
      light: yeti
    css: styles.css

editor: visual

execute:
  freeze: auto


